---
abstract: 'utilities to write and check a MANIFEST file'
author:
  - 'Andreas Koenig <andreas.koenig@anima.de>'
  - 'Michael G Schwern <schwern@pobox.com>'
  - 'Randy Kobes <r.kobes@uwinnipeg.ca>'
  - 'The Perl 5 Porters'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: ExtUtils-Manifest
requires:
  File::Basename: '0'
  File::Spec: '0.8'
  perl: '5.006'
resources:
  bugtracker: http://github.com/Perl-Toolchain-Gang/ExtUtils-Manifest/issues
  homepage: https://metacpan.org/release/ExtUtils-Manifest
  repository: git://github.com/Perl-Toolchain-Gang/Extutils-Manifest.git
version: '1.68'
x_Dist_Zilla:
  perl:
    version: '5.020000'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Filter/GatherDir'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Filter/PruneCruft'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Filter/ManifestSkip'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Filter/MetaYAML'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Filter/License'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@Filter/Readme'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Filter/ExecDir'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Filter/ShareDir'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Filter/MakeMaker'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Filter/Manifest'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Filter/TestRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Filter/ConfirmRelease'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Filter/UploadToCPAN'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::VersionFromModule
      name: VersionFromModule
      version: '0.08'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: CheckExtraTests
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: CheckChangesHasContent
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::OnlyCorePrereqs
      config:
        Dist::Zilla::Plugin::OnlyCorePrereqs:
          check_dual_life_versions: '1'
          deprecated_ok: '0'
          phases:
            - configure
            - build
            - runtime
            - test
          skips: []
          starting_version: 'to be determined from perl prereq'
      name: OnlyCorePrereqs
      version: '0.017'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: Test::MinimumVersion
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::DualLife
      name: DualLife
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: PodSyntaxTests
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.020'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.020'
x_authority: cpan:P5P
